### ISSUE TITLE
New versions are now crashing AzureLib

### ISSUE THREAD

**Issue by nvb-uy** [Sinytra/ConnectorExtras#29]
### Describe the bug

Connector Extras will crash AzureLib because it loads "too early", this doesn't happen on fabric.

### Steps to reproduce

1. Install Connector, Connector Extras and FFAPI
2. Install AzureLib for forge, and a mod that depends on it (like Eldritch End)
3. It will crash due to a geckolib compatibility mixin having a higher priority on the latest versions, since then, AzureLib will fail to load.

### Logs

https://mclo.gs/u5ythth

### Additional context

This seems to happen after [this mixin](https://github.com/Sinytra/ConnectorExtras/blob/5b22b019f3027067e8f0771ba7f7cf542b659296/geckolib-fabric-compat/src/main/java/dev/su5ed/sinytra/connectorextras/geckolibcompat/mixin/MinecraftMixin.java) was changed to have a priority of 2000. Older versions of Connector Extras make the mod load fine, and this also does not happen on fabric.

**Comment by Su5eD** [comment]
Whoops, seems like increasing the priority made the mixin inject *after* connector's early init entrypoint invoker, which meant that AzureLib was initialized before this mixin had a chance to apply.

I've fixed this in Connector by increasing the early init mixin's priority. This mixin in CE must keep its own priority in order to avoid a prior issue with Ultracraft. The fix will be available in Connector's next release, beta 38.
